name: Debug Destination Access
on:
  workflow_dispatch:  # Manual trigger

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4



    - name: Comprehensive PAT Test
      run: |
        echo "=== Testing PAT Permissions ==="
        
        # Test 1: Can we access the repo?
        echo "1. Testing repo access..."
        curl -s -H "Authorization: token ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mrfidget/all-of-the-sky | jq '{name, private, permissions}'
        
        # Test 2: Can we list branches?
        echo ""
        echo "2. Testing branch access..."
        curl -s -H "Authorization: token ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mrfidget/all-of-the-sky/branches | jq '.[] | {name, protected}'
        
        # Test 3: Check if we have push access
        echo ""
        echo "3. Testing push permissions..."
        response=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Authorization: token ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X GET https://api.github.com/repos/mrfidget/all-of-the-sky)
        echo "HTTP Status: $response"
        
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}
