name: Sync main to destination
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Private
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove workflow file
        run: |
          rm -f .github/workflows/Sync-Sky-Private-to-Sky-Public.yml
          rmdir .github/workflows 2>/dev/null || true
          rmdir .github 2>/dev/null || true

      - name: Configure Git
        run: |
          git config user.name "mrfidget"
          git config user.email "ferdie@ferdie.co.uk"

      - name: Push using store credential method
        run: |
          # Store the credential
          git config --global credential.helper store
          echo "https://${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Add remote without token in URL
          git remote add destination https://github.com/mrfidget/all-of-the-sky.git
          
          # Push using stored credentials
          git add .
          git commit -m "Sync from source repo - $(date)" || echo "No changes to commit"
          git push destination main:main --force