name: Sync main to destination
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Private
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove workflow file
        run: |
          rm -f .github/workflows/Sync-Sky-Private-to-Sky-Public.yml
          # Also remove the workflows directory if empty
          rmdir .github/workflows 2>/dev/null || true
          rmdir .github 2>/dev/null || true

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Test PAT access
        run: |
          # Test if we can access the destination repo
          curl -H "Authorization: token ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}" \
          https://api.github.com/repos/mrfidget/all-of-the-sky \
          || echo "PAT test failed"

      - name: Add destination remote
        run: |
          git remote add destination https://${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}@github.com/mrfidget/all-of-the-sky.git

      - name: Push to destination
        run: |
          git add .
          git commit -m "Sync from source repo - $(date)" || echo "No changes to commit"
          # Try without force first, then with force if needed
          git push destination main:main || git push destination main:main --force