name: Sync main to destination
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Private
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}  # <<< ADD THIS

      - name: Remove workflow file
        run: |
          rm -f .github/workflows/Sync-Sky-Private-to-Sky-Public.yml
          rmdir .github/workflows 2>/dev/null || true
          rmdir .github 2>/dev/null || true

      - name: Configure Git with PAT
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git config --unset-all http.https://github.com/.extraheader
          # Force Git to use our PAT for all operations
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}"

      - name: Add destination remote (without token in URL)
        run: |
          git remote add destination https://github.com/mrfidget/all-of-the-sky.git

      - name: Push to destination
        run: |
          git add .
          git commit -m "Sync from source repo - $(date)" || echo "No changes to commit"
          git push destination main:main --force