name: Sync main to destination
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Private
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove workflow file
        run: |
          rm -f .github/workflows/Sync-Sky-Private-to-Sky-Public.yml
          rmdir .github/workflows 2>/dev/null || true
          rmdir .github 2>/dev/null || true

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"

      - name: Add destination remote
        run: |
          git remote add destination https://${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}@github.com/mrfidget/all-of-the-sky.git

      - name: Debug Git Push
        run: |
          echo "=== Current remotes ==="
          git remote -v
          
          echo "=== Current branch ==="
          git branch -a
          
          echo "=== Git status ==="
          git status
          
          echo "=== Testing git ls-remote ==="
          timeout 30 git ls-remote destination || echo "ls-remote failed/timed out"
          
          echo "=== Attempting push with detailed output ==="
          GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_SSH_COMMAND="ssh -v" timeout 120 git push destination main:main --force 2>&1 | head -100
          
          echo "=== If above failed, let's try a different approach ==="
          # Try pushing a single file first
          echo "test" > test-file.txt
          git add test-file.txt
          git commit -m "Test push"
          timeout 60 git push destination main:main --force
          echo "Push exit code: $?"