name: Sync main to Public
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Private
        uses: actions/checkout@v4 

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action Sync"

      - name: Push to Repository Public
        env:
          PAT: ${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}
          REPO_B_URL: "https://github.com/mrfidget/all-of-the-sky" 
        run: |
          # Use the PAT for authentication to push to the public repo
          git push -f https://${{ secrets.SYNC_PRIVATE_TO_PUBLIC }}@github.com/mrfidget/all-of-the-sky.git main:main